-- Reset database schema to ensure clean state
DROP TABLE IF EXISTS reg_c100 CASCADE;
DROP TABLE IF EXISTS reg_d100 CASCADE;
DROP TABLE IF EXISTS reg_c500 CASCADE;
DROP TABLE IF EXISTS reg_c600 CASCADE;
DROP TABLE IF EXISTS reg_c010 CASCADE;
DROP TABLE IF EXISTS reg_0200 CASCADE;
DROP TABLE IF EXISTS reg_0140 CASCADE;
DROP TABLE IF EXISTS participants CASCADE;
DROP TABLE IF EXISTS import_jobs CASCADE;